### PR TITLE
Initial solution for windows mio problem #776

### PR DESCRIPTION
**Pull request by PerfectLaugh**
Refer to issue #776 
I don't know if it is elegant. But passed all tests in network section.
(Somehow I couldn't pass the a timer all the time, even with vanilla version)

### CODE REVIEW

**Comment by hawkw** [comment]
It looks like you've run `rustfmt` on _all_ the code in the project, not just the code added in this branch. That means that this diff appears to change a lot of code unrelated to your PR --- can we back that change out?

**Comment by PerfectLaugh** [comment]
oh sorry

**Comment by PerfectLaugh** [comment]
I thought it would not be pushed into this pull request

**Comment by PerfectLaugh** [comment]
but I will have to revisit what I've done here first

**Comment by PerfectLaugh** [comment]
Anyone can review it?

**Comment by carllerche** [comment]
Thanks for the PR. It is very intense and I will need to schedule a good chunk of time to review.

**Comment by PerfectLaugh** [comment]
Invalidate this Pull request for better improvement.

**Pull request closed without merging**
