### PR TITLE
Update windows-sys.

### PR DESCRIPTION
**Pull request by westy92**
Release notes: https://github.com/microsoft/windows-rs/releases/tag/0.59.0

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Should probably coordinate with Tokio on this.

/cc @Darksonn

**Comment by Darksonn** [comment]
Yes. I don't think we need to _force_ people to only use Tokio/mio combinations with the same windows-sys, but we should also update it in Tokio.

**Comment by Thomasdezeeuw** [comment]
@westy92 are you running the tests locally? Or only using the CI for testing?

**Comment by westy92** [comment]
@Thomasdezeeuw tests are passing on my Mac, but I am unable to test on Windows.

**Comment by Thomasdezeeuw** [comment]
Since this is failing the CI and no progress has been made to fix it I'm going to close this.

**Pull request closed without merging**
