### PR TITLE
feat: fallback to epoll_create when epoll_create1 not implement

### PR DESCRIPTION
**Pull request by honsunrise**
Fallback to epoll_create when epoll_create1 not implement.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
@honsunrise why do you need this change?

**Comment by honsunrise** [comment]
because some linux kernel not implement epoll_create1.
so tokio will panic when i run tokio on the system.

**Comment by Thomasdezeeuw** [comment]
> because some linux kernel not implement epoll_create1. so tokio will panic when i run tokio on the system.

What Linux version are you using? Because `epoll_create1` was added in v2.6.27, after https://github.com/rust-lang/rust/pull/95026 Rust will only support 3.2+.

**Comment by honsunrise** [comment]
v2.6.18

I did not use *-gnu toolchains, compile with the musl toolchains, it works on v2.6.18.
However, this PR is incomplete and the eventfd also needs to fallback.

**Comment by Thomasdezeeuw** [comment]
Kernel v2.6.18 is not supported. The minimum we supported was RHEL 6, kernel 2.6.32-754, but that is no longer maintained by RedHat. So, I think we'll want to increase our minimum support kernel to 3.2 based on https://github.com/tokio-rs/mio/issues/1561 and https://github.com/rust-lang/rust/pull/95026.

**Pull request closed without merging**
