### PR TITLE
Add test to list OS event details

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
This adds a simple test that print the system events in a specific scenario. This pr only include a couple scenarios for Unix pipes.

For further discussion in #1087.

/cc @carllerche @asomers

### CODE REVIEW

**Comment by carllerche** [comment]
In 0.6, I added some [TCP shutdown tests](https://github.com/tokio-rs/mio/blob/v0.6.x/test/test_tcp_shutdown.rs) that highlight some of the issues I mentioned.

I think somehow they were never ported to master or got misplaced in the shuffle?

**Comment by Thomasdezeeuw** [comment]
Doesn't seem that pr #944 was ever ported to master.

**Comment by Thomasdezeeuw** [comment]
Logs for some platforms.

MacOS:

```log
TcpStream connected and writable:
	EVFILT_WRITE|EV_ADD|EV_CLEAR|EV_RECEIPT
TcpStream readable:
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT
TcpStream shutdown reading side:
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
TcpStream shutdown writing side:
	EVFILT_WRITE|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
TcpStream shutdown both sides:
	EVFILT_WRITE|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
TcpStream remote closed:
	EVFILT_WRITE|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS

TcpListener incoming stream:
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT

UdpSocket writable:
	EVFILT_WRITE|EV_ADD|EV_CLEAR|EV_RECEIPT
UdpSocket readable:
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT

Unix pipe sender writable:
	EVFILT_WRITE|EV_ADD|EV_CLEAR|EV_RECEIPT
Unix pipe receiver readable:
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT
Unix pipe sender, receiver closed:
	EVFILT_WRITE|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
Unix pipe receiver, sender closed:
	EVFILT_READ|EV_ADD|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
```

Linux:

```log
TcpStream connected and writable:
	EPOLLOUT
TcpStream readable:
	EPOLLIN
TcpStream shutdown reading side:
	EPOLLIN
TcpStream shutdown writing side:
	EPOLLOUT|EPOLLHUP
TcpStream shutdown both sides:
	EPOLLIN|EPOLLOUT|EPOLLHUP
TcpStream remote closed:
	EPOLLIN|EPOLLOUT|EPOLLHUP

TcpListener incoming stream:
	EPOLLIN

UdpSocket writable:
	EPOLLOUT
UdpSocket readable:
	EPOLLIN

Unix pipe sender writable:
	EPOLLOUT
Unix pipe receiver readable:
	EPOLLIN
Unix pipe sender, receiver closed:
	EPOLLOUT|EPOLLERR
Unix pipe receiver, sender closed:
	EPOLLHUP
```

FreeBSD:

```log
TcpStream connected and writable:
	EVFILT_WRITE|EV_CLEAR|EV_RECEIPT
TcpStream readable:
	EVFILT_READ|EV_CLEAR|EV_RECEIPT
TcpStream shutdown reading side:
	EVFILT_READ|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
TcpStream shutdown writing side:
	EVFILT_WRITE|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
TcpStream shutdown both sides:
	EVFILT_WRITE|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
	EVFILT_READ|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
TcpStream remote closed:
	EVFILT_WRITE|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
	EVFILT_READ|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS

TcpListener incoming stream:
	EVFILT_READ|EV_CLEAR|EV_RECEIPT

UdpSocket writable:
	EVFILT_WRITE|EV_CLEAR|EV_RECEIPT
UdpSocket readable:
	EVFILT_READ|EV_CLEAR|EV_RECEIPT

Unix pipe sender writable:
	EVFILT_WRITE|EV_CLEAR|EV_RECEIPT
Unix pipe receiver readable:
	EVFILT_READ|EV_CLEAR|EV_RECEIPT
Unix pipe sender, receiver closed:
	EVFILT_WRITE|EV_ONESHOT|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
Unix pipe receiver, sender closed:
	EVFILT_READ|EV_CLEAR|EV_RECEIPT|EV_EOF|EV_SYSFLAGS
```

**Comment by Thomasdezeeuw** [comment]
@asomers, @carllerche continuing from the discussion in #1087, lets remove HUP from the name and instead call it disconnected (at least for this discussion). Epoll very inconsistent, while kqueue gives the exact flags you expect, see below.

`Event::is_read_disconnected`:

epoll:
 * `EPOLLIN` (TcpStream shutdown reading side), or
 * `EPOLLIN|EPOLLHUP` (TcpStream shutdown both sides, TcpStream remote closed), or
 * `EPOLLHUP` (Unix pipe receiver, sender closed).

kqueue (checked on macOS and FreeBSD): 
 * `EVFILT_READ|EV_EOF` (TcpStream shutdown reading side, TcpStream shutdown both sides, TcpStream remote closed, Unix pipe receiver, sender closed).

--------------------------

`Event::is_write_disconnected`:

epoll:
 * `EPOLLOUT|EPOLLHUP` (TcpStream shutdown writing side, TcpStream shutdown both sides, TcpStream remote closed), or
 * `EPOLLOUT|EPOLLERR` (Unix pipe sender, receiver closed).

kqueue (checked on macOS and FreeBSD): 
 * `EVFILT_WRITE|EV_EOF` (TcpStream shutdown writing side, TcpStream shutdown both sides, TcpStream remote closed, Unix pipe sender, receiver closed).

--------------------------

@carllerche in #1087 you mention that `EV_EOF` can be set in unexpected scenarios, can you add them to this pr so we can get an idea of what those scenarios are?

**Comment by carllerche** [comment]
I believe for `is_read_disconnected`, you mean `EPOLLRDHUP` instead of just `EPOLLIN`.

My vote is for `is_read_eof` and `is_write_eof`.

Re unexpected `EV_EOF`, I don't have time to write the PR this week (context switching is expensive for me), but I noticed that `kqueue` would generate `EOF` events based on syscalls taken on the local machine. So, you call `shutdown(...)` that resulted in a kqueue event w/ `EOF` set on the socket.

**Comment by Thomasdezeeuw** [comment]
> I believe for `is_read_disconnected`, you mean `EPOLLRDHUP` instead of just `EPOLLIN`.

I took the actual values from what Linux generated, see https://github.com/tokio-rs/mio/pull/1091#issuecomment-535598561. I would expect `EPOLLRDHUP` as well, but that didn't show in the test.

> My vote is for `is_read_eof` and `is_write_eof`.

Isn't eof too confusing? I know in Unix everything is a file and all, but "end of stream" or something would be more accurate, especially since Windows doesn't use the everything is a file terminology.

> Re unexpected `EV_EOF`, I don't have time to write the PR this week (context switching is expensive for me), but I noticed that `kqueue` would generate `EOF` events based on syscalls taken on the local machine. So, you call `shutdown(...)` that resulted in a kqueue event w/ `EOF` set on the socket.
> 
> IIRC, if you do `shutdown(WRITE)`, that will result in getting an event `EVFILT_WRITE | EV_EOF`.

Yes if you call `shutdown(Shutdown::Write)` you'll get an event with `EVFILT_WRITE` and `EV_EOF` see (see https://github.com/tokio-rs/mio/pull/1091#issuecomment-535598561), but that is what we want. The `EOF` is a bit misleading, but it means (in combination with `EVFILT_WRITE`) that you can't write any more.

**Comment by carllerche** [comment]
We could do `is_write_closed`? I don't care that much, i'm happy to go w/ whatever.

**Comment by Thomasdezeeuw** [comment]
I'm ok with `is_read_closed` and `is_write_closed`.

**Comment by kleimkuhler** [comment]
@Thomasdezeeuw have you made any progress on `is_read_closed`/`is_write_closed`? I'm looking to update Tokio to mio 0.7 soon and I think this is one of the last things that needs to get done for that. If you haven't had the chance yet, I may start working on it if that is okay!

**Comment by Thomasdezeeuw** [comment]
@kleimkuhler I created these tests to see what epoll/kqueue events where created in which scenarios to determine what events should trigger `is_read_closed`/`is_write_closed` and haven't been able to spend more time on it since. I was planning on working on it this weekend, but feel free to work on it.

**Comment by kleimkuhler** [comment]
@Thomasdezeeuw Sounds good. I should have some time this week to start working on it.

Meanwhile, this PR of course seems helpful for that. Was it just opened to show the events for each platform, or would you like a quick review as well? I don't see any major blockers on it.

**Comment by Thomasdezeeuw** [comment]
I would like to get this merged in some form, but the code as is is quick
and dirty (e.g. file descriptors aren't closed). But most of these can be
used as tests for `is_reaf_closed`/`is_write_closer` after a bit of cleanup.

**Comment by kleimkuhler** [comment]
@Thomasdezeeuw I've opened #1110 as a draft PR to show an initial implementation of `is_read_close` and `is_write_close` methods on all platforms.

`kqueue` platforms are fairly straight forward as expected.

`epoll` platforms require explicit registration of `EPOLLRDHUP` when registering interest in the socket. Because `mio` only supports edge triggered notifications this should be expected from reading [EPOLLRDHUP](http://man7.org/linux/man-pages/man2/epoll_ctl.2.html) documentation.

The main reason this is a draft is because the windows implementation needs to be changed and tests still need to be added. I'd like for this PR to be merged, but it will probably require some more significant changes to use this functionality as part of tests. I may plan on opening a PR against your branch so that this can merge first?

**Comment by Thomasdezeeuw** [comment]
@kleimkuhler I think you're right about `EPOLLRDHUP`, I've updated my comment above (https://github.com/tokio-rs/mio/pull/1091#issuecomment-535598561).

**Comment by Thomasdezeeuw** [comment]
Closing this as its implemented in #1110.

**Pull request closed without merging**
