### PR TITLE
 Add Interests::and 

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
This allows adding two interests together, much like the BitOr
implementation, but is a constant function.

I'm not 100% sure on the name, as people might conflict it with `BitAnd`, however `or` didn't make sense either.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I've been thinking but haven't found any good name for the method. My current favourite is `add`.

**Comment by carllerche** [comment]
Let's go w/ `add` then 👍

**Comment by Thomasdezeeuw** [comment]
Clippy is complaining that we should consider implementing `std::ops::Add` instead of adding an `add` method. Maybe `add` isn't the best option then.

**Comment by carllerche** [comment]
We can silence clippy here imo

**Pull request merged**
