### PR TITLE
Fix docs typo in TcpStream connect

### PR DESCRIPTION
**Pull request by oliverjantar**
Fixing typo in docs TcpStream connect function

### CODE REVIEW

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Noah-Kennedy** [comment]
Looks like a spurious network failure.

**Comment by Noah-Kennedy** [comment]
@oliverjantar could you push an empty commit to restart CI?

**Comment by Thomasdezeeuw** [comment]
We could have just restarted the CI, no need for an empty commit, but I approved the run.

**Comment by Thomasdezeeuw** [comment]
Thanks @oliverjantar.

**Pull request merged**
