### PR TITLE
Implement Evented for any type Deref<Target = Evented>

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**

### CODE REVIEW

**Comment by carllerche** [comment]
I think this strategy is fine. There is a slight forwards compatibility risk as adding a blanket impl could block some impl we might want in the future, but `T: Deref` is pretty conservative.

**Comment by Thomasdezeeuw** [comment]
@carllerche So do you want to commit to this? Then I'll rebase.

**Comment by carllerche** [comment]
Your decision either way.

**Comment by Thomasdezeeuw** [comment]
I think it's worth it.

**Pull request merged**
