### PR TITLE
handle unexpected_cfgs

### PR DESCRIPTION
**Pull request by dswij**
See e.g. https://github.com/tokio-rs/mio/actions/runs/8986077701/job/24682502223 due to https://github.com/rust-lang/cargo/pull/13571

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I meant remove all the CI setup stuff, just `#![allow(unexpected_cfgs)]`.

**Comment by Darksonn** [comment]
You probably need `#![allow(unknown_lints, unexpected_cfgs)]`. See also https://github.com/tokio-rs/tokio/pull/6538.

**Comment by Urgau** [comment]
Heads up, with the release of rust-lang/cargo#13913 (in nightly-2024-05-19), there is no longer any need for the kind of workarounds employed in this PR. Cargo has now gain the ability to declare `--check-cfg` args directly inside the `[lints]` table with [`[lints.rust.unexpected_cfgs.check-cfg]`](https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html#check-cfg-in-lintsrust-table)[^1]:

`Cargo.toml`:
```toml
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(foo)'] }
```

> Note that the diagnostic output of the lint has been updated to suggest the `[lints]` approach first. You can use it to guide you through the `--check-cfg` arguments that may need to be added.

[^1]: take effect on Rust 1.80 (current nightly), is ignored on Rust 1.79 (current beta), and produce an unused warning below

**Comment by Thomasdezeeuw** [comment]
Closing in favour of #1787, which adds the two expected cfgs instead of ignore the lint (since I think it's quite useful for Mio).

**Pull request closed without merging**
