### PR TITLE
Removed `try_clone` Unix UDS impl 

### PR DESCRIPTION
**Pull request by dtacalau**
(associated tests were also removed) This api had several limitations . More details in issue #1074.

`try_clone` was just a dup, so the behavior depended on the underlying epoll
and kqueue implementations. This meant there was no defined behavior because of
the platform dependent differences between epoll and kqueue implementations.

Signed-off-by: Daniel Tacalau <dst4096@gmail.com>

### CODE REVIEW

**Comment by dtacalau** [comment]
@kleimkuhler

**Comment by dtacalau** [comment]
rebased on master after merging #1180

**Comment by kleimkuhler** [comment]
Clippy, but looks good

**Comment by dtacalau** [comment]
> LGTM, sans the Clippy issue.

Clippy seems happy now.

**Comment by Thomasdezeeuw** [comment]
@dtacalau thanks.

**Pull request merged**
