### PR TITLE
remove dependency to hermit-abi

### PR DESCRIPTION
**Pull request by stlankes**
- use directly libc as platform interface

### CODE REVIEW

**Comment by stlankes** [comment]
Ok, we have to wait for the missing error numbers. see rust-lang/libc#3858

**Comment by stlankes** [comment]
A new version of libc is published and the dependency to hermit-abi can be removed. But I don't understand that `CI / Sanitizer (leak)` failed. Does someone have an idea? I just use a new version of libc.

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
@stlankes the CI can be ignored it's a sanitizer issue, Mio is not to blame.

**Comment by Thomasdezeeuw** [comment]
Thanks @stlankes

**Comment by stlankes** [comment]
@Thomasdezeeuw Do you know, when you publish a new release? I would prefer to remove this dependency from the latest release.

**Comment by Thomasdezeeuw** [comment]
I'll prepare a release now. I don't really have a schedule for them.

**Pull request merged**
