### PR TITLE
Fix various Clippy lints

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Also see #1776

### CODE REVIEW

**Review by Darksonn — APPROVED** [review]
Looks like you missed one.
```
error: read amount is not handled
  --> tests/close_on_drop.rs:62:23
   |
62 |                 match self.cli.read(&mut buf) {
   |                       ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: use `Read::read_exact` instead, or handle partial reads
note: the result is consumed here, but the amount of I/O bytes remains unhandled
  --> tests/close_on_drop.rs:64:21
   |
64 |                     Ok(_) => panic!("the client socket should not be readable"),
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
   = note: `#[deny(clippy::unused_io_amount)]` on by default
```

**Comment by Thomasdezeeuw** [comment]
I just love how it switches between some 1 error in the tests, then 1 error in the examples and back to the tests again...

**Comment by Darksonn** [comment]
My guess is the rustc version. Clippy lints can vary a lot.

**Comment by Thomasdezeeuw** [comment]
Doesn't seem to trigger any more? At least not on the CI.

**Pull request closed without merging**
