### PR TITLE
Use tempfile instead of tempdir

### PR DESCRIPTION
**Pull request by JohnTitor**
tempdir has been deprecated and using tempfile is recommended.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Can do without this dependency? I don't really have the time to review another dependency right now.

**Comment by JohnTitor** [comment]
The implementation here is hard a bit. Actually, tempfile is using tempdir API (see: https://github.com/Stebalien/tempfile/pull/33) so the behavior shouldn't be changed. And it's just a dev-dependency so the effect is quite small.
But if you still have concerns, I'll close this or leave until you review it.

**Comment by Thomasdezeeuw** [comment]
Removing the dependency wasn't too much work: #1239.

**Comment by Thomasdezeeuw** [comment]
#1239 removed the dependency.

**Pull request closed without merging**
