### PR TITLE
Update windows-sys to 0.52

### PR DESCRIPTION
**Pull request by westy92**
Land https://github.com/tokio-rs/mio/commit/eea9e3e0c469480e5c59c01e6c3c7e5fd88f0848 on `0.8.x` to unblock updating `windows-sys` in `tokio`.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Duplicate of #1725. Can't be accept in v0.8 because windows-sys bumped the MSRV to be higher than what Mio supports.

**Comment by westy92** [comment]
Can we bump MSRV to 1.56 now that it's after March 2024?

https://github.com/tokio-rs/mio/pull/1725#issuecomment-1840332722

**Comment by Thomasdezeeuw** [comment]
I rather move forward with Mio v1, for which I don't have enough time as it is.

**Comment by westy92** [comment]
Fair enough. Thank you for your work on v1!

**Pull request closed without merging**
