### PR TITLE
Fix Clippy warnings and add it to CI

### LINKED ISSUE #891: Run clippy on travis
Since https://github.com/carllerche/mio/pull/889 was merged, do you guys think it would be valuable to run clippy on Travis? I could take this one ;)

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Closes #891.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
For what ever reason the cross compile build for NetBSD is using Rust 1.35. I don't know why, or how to fix it. Other then that this should be ready for review.

**Comment by asomers** [comment]
Perhaps your azure image already comes with rustup installed at 1.35, so rustup doesn't update it?  If that's the problem, you could try either changing clippy's rust version from stable to 1.36, or do a rustup update stable after installing rust.

**Comment by carllerche** [comment]
@Thomasdezeeuw this is correct, azure changed stuff with regards to rust which broke a bunch of CI :(. The `azure-install-rust.yml` file can be changed to [this](https://github.com/tokio-rs/tokio/blob/master/ci/azure-install-rust.yml).

**Comment by Thomasdezeeuw** [comment]
Fixed the build on NetBSD, now need to fix the Clippy check.

**Comment by Thomasdezeeuw** [comment]
Seems to work now, I'll rebase this on master.

**Pull request merged**
