### PR TITLE
Add `into_std` methods to structs with `from_std` methods

### PR DESCRIPTION
**Pull request by stevenroose**
It seems useful to have those.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I don't think this is a good idea since the type in standard lib are generally consider blocking, while Mio's types are generally considered non-blocking.

**Comment by stevenroose** [comment]
About the CI failure, it seems like it's unrelated. I don't get it locally, but I occasionally get other failures.

**Comment by Thomasdezeeuw** [comment]
Yeah it's a known problem: #1376, I've restarted the CI.

**Comment by Thomasdezeeuw** [comment]
> Well the same is true for `from_std`, right? 

That's true. 

> And there's a disclaimer about that on `from_std`, so I also added a disclaimer about that on `into_std`. I can make the disclaimer a bit more explicit about the non-blocking state?

The problem with going Mio -> std, is that Mio keeps some additional state (on Windows) that will get lost. For everything to guarantee to work correctly you would need to `deregister` before calling `into_std`. And `register` when doing the inverse again, i.e. `from_std`.

Can you add two tests for each type:

1) A tests that creates a Mio TcpStream/UdpSocket/etc. register it with `Poll`. Create an event for it (accept the stream/send a packet etc.). Next deregister it and call `into_std`. Then check that we get no events for the type (you can use `expect_no_events` for this).
2) Basically the same as above, create Mio type, register, create event, deregister and call `into_std`. But then call `from_std` and register it again. After that poll and we would expect to get an event (but I'm not 100% sure this will be the case).

**Comment by Thomasdezeeuw** [comment]
@stevenroose do you plan on continuing this?

**Comment by Thomasdezeeuw** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
