### PR TITLE
Add minimal versions test to CI

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
We no longer use Travis and we test the minimal Rust version, so closing. Thanks @cramertj.

**Comment by cramertj** [comment]
@Thomasdezeeuw this is for testing minimal versions of dependencies (as specified in the Cargo.toml file), not testing against a minimum version of Rust itself.

**Comment by Thomasdezeeuw** [comment]
Sorry completely missed that.

**Comment by Thomasdezeeuw** [comment]
Done in #1058.

**Pull request closed without merging**
