### PR TITLE
Use published lazycell

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Pr #887 removed lazycell because 1.2 required Rust 1.20 (based on the comment in #886), but master is now on 1.34+ (Rust 2018) right? So I think this is fine.

**Comment by lnicola** [comment]
Yes, that was my reasoning.

**Comment by Thomasdezeeuw** [comment]
I'll leave this up to @carllerche to decide whether or not to merge since I haven't reviewed lazycell.

**Comment by carllerche** [comment]
IMO there is a deeper problem w/ the lack of definition around `rustc` backwards compat and crate versions.

If anything, mio should strive to have fewer dependencies rather than more.

**Comment by carllerche** [comment]
i.e. while `lazycell` may work today, there is no guarantee the dependency will maintain the backwards compat that `mio` would like.

**Comment by lnicola** [comment]
We can choose to stick to an older version of `lazycell` if it ends up dragging another version of the compiler. Let's cross that bridge when we get there. It's not a large dependency, but I don't think it makes sense to vendor it like this.

> here is no guarantee the dependency will maintain the backwards compat that mio would like

Does `mio` have a policy wrt. the minimum compiler version?

**Comment by lnicola** [comment]
See https://github.com/rayon-rs/rayon/issues/586 for a similar issue about supported compilers and upgrading dependencies.

**Comment by lnicola** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
