### PR TITLE
Test refactor continued

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Creates the following output (for the functional tests):

```log

     Running target/debug/deps/functional-740432e6e33d57cd

running 1 test
test tests::poll::test_poll_closes_fd ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

The we would have three categories; unit, functional and end to end, and of course the doc tests. Seems pretty good to me.

**Comment by Thomasdezeeuw** [comment]
Cargo fmt fails with `Error writing files: io error: Failed to find module poll in "functional" None`. Rustfmt rustfmt doesn't understand the `path` attribute: https://github.com/rust-lang/rustfmt/issues/1208.

**Comment by asomers** [comment]
Cool!  What happens if you remove the `path` attribute?

**Comment by Thomasdezeeuw** [comment]
Then we can't import poll, as it will look for `tests/poll.rs` or `tests/poll/mod.rs`.

**Comment by asomers** [comment]
Well, what would happen if you eliminated both `#[path]` and the `mod tests`?

**Comment by Thomasdezeeuw** [comment]
I'm stupid. I started with just having `mod poll` (not in a module) in the file and that didn't work. But just adding `mod functional { mod poll }` works, no need for `path`.

**Comment by Thomasdezeeuw** [comment]
@carllerche you also ok with this layout? If so I'll update #1030 with this structure.

**Comment by Thomasdezeeuw** [comment]
Ok, rustfmt failed again but this this it's just a bug I think.

**Comment by Thomasdezeeuw** [comment]
I think it's https://github.com/rust-lang/rustfmt/issues/3572.

**Comment by carllerche** [comment]
@Thomasdezeeuw I'm fine w/ the structure, but how do you plan to deal w/ the rustfmt bug?

**Comment by Thomasdezeeuw** [comment]
I don't yet, I've just asked in https://github.com/rust-lang/rustfmt/issues/3572 for a work around. Maybe we should just merge #1019 as is and move this structure if/when we find a work around or a fix.

**Comment by carllerche** [comment]
@Thomasdezeeuw Yeah, lets just merge #1019 and wait for a fix. Thanks for trying out this option :+1:

**Comment by Thomasdezeeuw** [comment]
I've force pushed some changes, these use a (too complicated) macro to set the path correctly for each file as a workaround for the rustfmt bugs. A downside is that I'm pretty sure that rustfmt doesn't reach and formats the files anymore, but at least it won't return an error.

**Comment by Thomasdezeeuw** [comment]
What you think about the macro approach? It isn't great, but I don't really see another way to get it to work currently.

**Comment by carllerche** [comment]
Up to you, but IMO it isn't worth going against the grain and I would just stick with #1019.

**Comment by Thomasdezeeuw** [comment]
Rustfmt fails with yet anther issue, but I wanted to get some feedback first. @carllerche, @asomers what do you think of the new output.

**Comment by carllerche** [comment]
My vote is still to follow `cargo` idioms, but I will go with whatever :)

**Comment by asomers** [comment]
I like it.  It's just what I had in mind.  Too bad about that annoying rustfmt bug, though.

**Comment by Thomasdezeeuw** [comment]
The last commit works around the last rustfmt bug, however Azure doesn't seem to want to run. Any way to start it manually?

**Comment by Thomasdezeeuw** [comment]
I'm closing this for now, to many rebase conflicts.

**Pull request closed without merging**
