### PR TITLE
Update to windows-sys v0.52

### PR DESCRIPTION
**Pull request by skyfloogle**
This is just a cherry-pick of the corresponding commit from the master branch. Required for building on certain targets on newer versions of Rust (see https://github.com/microsoft/windows-rs/pull/2774).

### CODE REVIEW

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
Cherry-pick of commit eea9e3e0c469480e5c59c01e6c3c7e5fd88f0848.

Note to self add this to the commit when merging.

**Comment by skyfloogle** [comment]
Looks like this would require a MSRV increase to v1.56, which I understand goes against mio's policy. Does this mean building these targets on Rust v1.76+ will have to wait until v1.0 is stabilized?

**Comment by Thomasdezeeuw** [comment]
> Looks like this would require a MSRV increase to v1.56, which I understand goes against mio's policy. Does this mean building these targets on Rust v1.76+ will have to wait until v1.0 is stabilized?

Yes, I'm afraid so.

**Comment by skyfloogle** [comment]
In that case, I'll close the pull request.
On the bright side, after further investigation, I found out this doesn't actually block me, as my project only uses `mio` as a transitive dependency which isn't actually invoked on Windows.
Apologies for the confusion, and good luck with future developments!

**Pull request closed without merging**
