### PR TITLE
Test with minimal versions on CI

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Continuing #878.

/cc @cramertj

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Well it worked and we found the first problem.

**Comment by asomers** [comment]
Sadly `-Zminimal-versions` is nearly useless unless all of your dependencies (and all of their dependencies) also use it in CI.  It probably won't be possible for most crates to use it until a `-Zminimal-versions-for-me-but-not-my-dependencies` gets added.  See https://github.com/rust-lang/cargo/issues/5657 .

If you merely do `cargo check` instead of `cargo test` with minimal versions, does that pass?

**Comment by Thomasdezeeuw** [comment]
I found the problem, it's `bytes` that uses `iovec` v0.1.0 which uses `winapi` v0.2. But we only use `bytes` for testing, so `cargo check` works fine (assuming you don't add `--tests`).

**Comment by Thomasdezeeuw** [comment]
It seems `bytes` v0.5 (unreleased) doesn't have `iovec` as a dependency any more, which would solve this problem, but I don't know when that would be released.

**Comment by carllerche** [comment]
@Thomasdezeeuw simultaneously w/ mio probably... we can switch to a git dependency on bytes master.

**Comment by Thomasdezeeuw** [comment]
Ok, will do.

**Comment by Thomasdezeeuw** [comment]
Created #1059.

**Comment by Thomasdezeeuw** [comment]
CI is green.

**Pull request merged**
