### PR TITLE
impl Clone for Event

### PR DESCRIPTION
**Pull request by LuoZijun**

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I think `Event` is too big for `Copy`, e.g. `kevent` is 32 bytes. Do you have a use case for `Clone`?

**Comment by LuoZijun** [comment]
@Thomasdezeeuw 

Yes, for example, when I receive a readable event, but I don't want to start processing the event immediately, so I want to put the event in a delay queue and then process it at a suitable time. At this time, I need Event to be Clone.

**Comment by LuoZijun** [comment]
@Thomasdezeeuw `Copy` has removed.

**Review by Thomasdezeeuw — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
Thanks @LuoZijun.

**Pull request merged**
