### PR TITLE
Work around 32 bits epoll_wait() bug (#1349)

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
A bug in kernels < 2.6.37 makes timeouts larger than LONG_MAX /
CONFIG_HZ (approx. 30 minutes with CONFIG_HZ=1200) effectively
infinite on 32 bits architectures. The magic number is the same
constant used by libuv, see commit libuv/libuv@d1b5008e76.

Backport of #1349 to v0.6.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
@carllerche can you force commit this? I don't want to change more in the code to fix all Clippy lints.

**Comment by Darksonn** [comment]
It seems like the trouble is with the min-rust test, not clippy?

**Comment by Thomasdezeeuw** [comment]
@Darksonn you're right the log crate seems to have updated there minimum rustc version.

**Review by carllerche — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
@carllerche can you force merge this? The CI is failing because we 0.6.x still supports older Rust version, but we know the changes are good.

**Pull request merged**
