### PR TITLE
Handle ERROR_MORE_DATA in reading from Windows named pipe

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Closes https://github.com/tokio-rs/tokio/issues/6460

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I don't really have a way to test this. I don't know how to create the "error" conditions such that it trigger this code branch. It was manually tested by @MolotovCherry, see https://github.com/tokio-rs/tokio/issues/6460#issuecomment-2040270414.

**Comment by MolotovCherry** [comment]
Just for transparency, here's my testing code below. On the original issue, one can find the other original failing case.
```rs
use tokio::{
    io::{AsyncReadExt as _, AsyncWriteExt},
    net::windows::named_pipe::{ClientOptions, ServerOptions},
    task,
};

#[tokio::main]
async fn main() {
    const BUFFER_SIZE: usize = 4096;

    const PIPE_NAME: &str = r"\\.\pipe\foobar";

    let h = task::spawn(async {
        let mut buf = vec![0; 4096];

        let mut server = ServerOptions::new()
            .access_inbound(true)
            .access_outbound(true)
            .reject_remote_clients(true)
            .pipe_mode(tokio::net::windows::named_pipe::PipeMode::Message)
            .in_buffer_size(BUFFER_SIZE as u32)
            .out_buffer_size(BUFFER_SIZE as u32)
            .create(PIPE_NAME)
            .unwrap();

        if server.connect().await.is_err() {
            panic!();
        }

        let Ok(size) = server.read(&mut buf).await else {
            unreachable!()
        };

        println!(
            "{size:?}: buf: {:?}",
            std::str::from_utf8(&buf[..size]).unwrap()
        );

        let Ok(size) = server.read(&mut buf).await else {
            unreachable!()
        };

        println!(
            "{size:?}: buf: {:?}",
            std::str::from_utf8(&buf[..size]).unwrap()
        );
    });

    let c = task::spawn(async {
        tokio::time::sleep(std::time::Duration::from_millis(50)).await;
        let mut client = ClientOptions::new().open(PIPE_NAME).unwrap();

        client.write_all(b"osrckodsjvetogpzljchmxgydobdxcvnuycomvmqigmdyhcwoviukhtugkdsrxvnjpiwvddlkaoxncdjosuyetvzymzywkpohlfvbascszryatuvycbuvuzhlnurwxwynjhvhuxjpsosvvtuqfynxnspzjblpjsjkbxfvwwehcxcloojqunfgltxivfsvzegellljmrzxfshatwfjpuoggvqhaclpvmsdbhjjpeamdxvzsmzzqaxpfygbcjmehgbvkrbjbhohvkwcjgbslhrhjblvdqnsjlqtliocomcbubzqxjtahgikfdhbqrrkllewwepdcwguccammwqwscxxndoxrtxaklizcazmeillcztrfkgmvajkpkuytgpaxinkarermlhartmmfnruyweebpmfefmawpdjayfdvupyrbngvdqekhgixpzmgnbfvxvlsxxngvozwkulyoyfwvoqgjijpwzjmmlnjesfamndspeofpfscgejgexyxzdxbyvxysftscenbqroocahwtqkyllxcbivecmoxrfbatnllhxwotapvnniiptcebdqbjchpkhgbqktemykczsatdsxzhtezeypdfwslonqjzcehfcloldoonjpcwufvullfmqlgymqrumeanyffaykakvcqimmrvqmjuahjjozrwgunwlstnhhgdxttamfeerecxzvrhkixjsviwyuihdvekbkucuipqqzekipwutbzofnumzcpflhskjneszjhsbhdtripilzprgcuemgvkvumldktiydmvlehmhvhxybubvsshhoydounbcxzzbqsiytlwdjrwuerhknkjjskjcohznmmbdfsrhyoijxtxeboppbcyvvmeyymlwlzqlnalbgaowlpdvldqagyukvyuuumyozkpbykcqlrbdhyyixaessdgpswepmwacaenioouvumztmwaoihjrxltmavktsduvvmiuytocjxxerndpyixkjfeoncbsgbllkxetmssrcjurccjcjfqwnfwejhxdmlielbfhhbanmozvbuudvdraydpfwgshspvimhvhsooporslglkcnlpjxsbnfndsdxejuyonlgzwakbjebeqmxchdwpdvnkymwmkbtohmxgvilyqckzlhtsbmlosemblxzivjhdchndvhxsbxnjsjsmcrbhyjsrengmgyxsrzkvrmgslwqwyvtacqpotcutsczdsmmbclwjlxvtcyrhwnteyirgmpwqkvehqazhtaqcixaafbiyjbptttjlcblamzbdribivcfimbgrzwdhvjjtjkxibpbvorecuuqpxsfpzxcurysqfczppsbubwaemvglubrncwbccorntogpxspcziabbsnciqehzkapjozxsujnkjepretcczzviiztonpojcswmbkfonsdzdefihvpixmvraepoyyrkzbdyppcdeivksvxfdlvgxpivpfhzlkbuhmxpozzqjbqvlgvxefqiurhspjblgxxeqcjmzhybrlwxcypifprgqkwbncumvqezijdnahyxnwowclohwhhoiyajsymlikvlzyftxcckjfqueodhyhibdpjmpfbqikqvvbpmllevtgimcteryhiqgugzvjwvlbztditseqgtfffkdwavavaqxfbaeehddgwuhktkyfzwrpahoqpmmmsgpkiehkxxwbommitjvinzyctmgurlakpysitavtfxdcbxyhthedegmdbcguugbwjmvukfzygylrbbvrpmwvffpwqttrdkgxsqhgcfqbqvcaednudmglpvcqqkxkbspvrmdntldejyskonznrpzluojqonocuqptqbifxfzbhjxpfatyobpfeocqpelayxotfmruepgmjjtkudfdbgnwpnvlgxpmkwjkxsnsnjkhqharpbuauuobzlqssqfzmtnsmydabkauxdqsthxjiifymagtsswythqhpptzljrtzajhdpgqhjcvobezzqwxzcxevnwscaoailhnppvovgvlakhwzlwuygpkgjhztsgdzfoavbysbacruhzdodipoyqvsuqmtjsjdqfapsqcnngqqfrqaykqmfnlwllcflddvatvwboaaychpgrfvelfzscjmchywakkichpedhrdqbrabslwuqrkofaomzfftaezchbddhqtemwdelhuvfoddfhdtkcshophgslwocghcuyoakfrjsuryicgruiqcllrnhmsnvbfkunyeuzwgqulplmdgvxirhafcmlxwpferuauecitaoxeqbsnmouskhypntxgdcznbppghqvuoeavsrrmdlevqmcgonmbbwgajewftwublgddjrmkmksicqzfitvtabrqovjjhdkryemzbqgqpyeicrndwvsqnaxilbqduwrrctjnbysmjdbqtpqptscztjjzdzzrlakosvoftspewclfkdjnakogmuhtzdmvzosgfbyudrtejjvoalspebaiaikqsslbxfnejpxclvvyvxzclzyhfjvzxprpmejhsxvaebgfzyqnfymybyukuawsouijaqdigvciqndnltkipivgnrnwnvsxihnxhmultkazeddyepsvysbgsnbmfsjaspehncokeyqmcprjqxvrlxoyduoabcakftxjvevlladzmfxvgndzgrfmbokwpkuxzpyqyoeevdicuxsbmtahwuiptqruvkjnuxrtsdjshckoluylzgbmqqjphhclblesgwvnxupulztpwpvjlqtehncmlhzijyhrmovbncxjisyywrrjczwxoycnhyyvbimtdzoixjocpyrwfzfpikteyfrcadhiqmlibpsnsphxksgxlcxxlrzmcczubixhtdoevlasnjcvxjyxyqfajdcpmfmnpxcpoizhxlfjynjcxrijnifyoguabidgkzxhdcqfnnmzzbxgbnzikejfaoogucovgjvlmohddjsubfofdarmzqzwyidsvzidcjwrmagscmzrfqbpbutqrtmlxfttiuywlhtznfhyogdfqtdvvvqoamldklleubwplhdncjsfnccincrnirfbcanthwiiibthxceissbelfurrvbfqonxsxjrwytjfweqwedvzrnizjcmxxpfrennqmdhxpkygdgicckvvoudorqcxmfdipiqtbmrncuwjhqhklercxqzscwfwmkswmxveiosskpizhoglbqpqwewzqwlkftcrrdfbtvrxspkligxpjjjmanlqspaqzseftecqimeullspepcqsztktaapyrhznwutjuqgjkdioueoixppxfnkktbfkyiqlaccastkjupqgvhmmiczadfrarhrwrekhfxwiufhpbhgaykyghltuhlrnosegrihiivnfhkxwjhewbtylfralhkawiazxmqgtewirwjtkavhdbizujklwrtoxatguiqgromiibhvyxoihwanrpryevvopzmtwogqwjrnwlezhrywctcgdouowuaxwdtngbglibbqvrcgqpkhplhpwniuetixppcpcsfwclkqbfwfgvtthqtjomtiolumvazlwgtlbpacilmgnknmdvzdhsannfoazlitsgjumouigmvywvwdsetozojhhbbajwdrienxgqxbbcjrxlwwshbinjjvjcnvgoxnkvppffkaljlvcoxokyazcfqgzxcastntssmuzayllzcnljapjgeygnxgxwjeydybnwkelqybaxtunnuuzcxslddihcrxgpjxbiescrygmxpmtwviwffypbnpgjmipmfaajdymaqggdscopyempytgcioqyjtbemyvdwkfdclfcessaqiepbavmiguxasnuydmpcyuhxiwyicpdwvqhpvzhpivnrgsrcsttjsisqdvdlgecaevqqdssazhchsbxbixzlpctmhsmicmlspczdoghocgioxjlkmkvxjgegmufchblogabsuigjzddcagqseowsnkvtbbatbrpibnyvincfmousmlpoosxzjyloddnyjxxviivpyxipcoinxywhbuaersyovypgt_overwrite").await.unwrap();
    });

    h.await.unwrap();
    c.await.unwrap();
}
```

**Comment by Darksonn** [comment]
Does this actually behave correctly for large buffers with pipe mode message? Let's say we passed a larger buffer to `read`, then mio would still only use 4kb internally for the operation, but with pipe mode messages, the reads are supposed to correspond to individual messages.

Or maybe it's okay to split up messages in multiple reads because of the ERROR_MORE_DATA error.

**Comment by MolotovCherry** [comment]
> Does this actually behave correctly for large buffers with pipe mode message? Let's say we passed a larger buffer to `read`, then mio would still only use 4kb internally for the operation, but with pipe mode messages, the reads are supposed to correspond to individual messages.
> 
> Or maybe it's okay to split up messages in multiple reads because of the ERROR_MORE_DATA error.

I set the in/out buffer to 8k, and also the read buffer as well. I still receive the same result as normal. Everything is split up in messages determined by each write. And if the write is > 4096, it splits that one up into 2.

**Comment by Darksonn** [comment]
Hmm. Perhaps the overlapped callback runs twice with ERROR_MORE_DATA for the follow-up?

@MolotovCherry What is the value of `io.read` when you hit that `unreachable!()`?

**Comment by MolotovCherry** [comment]
> Hmm. Perhaps the overlapped callback runs twice with ERROR_MORE_DATA for the follow-up?
> 
> @MolotovCherry What is the value of `io.read` when you hit that `unreachable!()`?

@Darksonn I added a println for `io.read` at this line (before this statement)
https://github.com/tokio-rs/mio/blob/ac406235e8e12b95f9b500c6200410ffd89ff10f/src/sys/windows/named_pipe.rs#L869

Here are the results:
```rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `R:\rust\debug\f.exe`
Pending([], 0)
4096: buf: "osrckodsjvetogpzljchmxgydobdxcvnuycomvmqigmdyhcwoviukhtugkdsrxvnjpiwvddlkaoxncdjosuyetvzymzywkpohlfvbascszryatuvycbuvuzhlnurwxwynjhvhuxjpsosvvtuqfynxnspzjblpjsjkbxfvwwehcxcloojqunfgltxivfsvzegellljmrzxfshatwfjpuoggvqhaclpvmsdbhjjpeamdxvzsmzzqaxpfygbcjmehgbvkrbjbhohvkwcjgbslhrhjblvdqnsjlqtliocomcbubzqxjtahgikfdhbqrrkllewwepdcwguccammwqwscxxndoxrtxaklizcazmeillcztrfkgmvajkpkuytgpaxinkarermlhartmmfnruyweebpmfefmawpdjayfdvupyrbngvdqekhgixpzmgnbfvxvlsxxngvozwkulyoyfwvoqgjijpwzjmmlnjesfamndspeofpfscgejgexyxzdxbyvxysftscenbqroocahwtqkyllxcbivecmoxrfbatnllhxwotapvnniiptcebdqbjchpkhgbqktemykczsatdsxzhtezeypdfwslonqjzcehfcloldoonjpcwufvullfmqlgymqrumeanyffaykakvcqimmrvqmjuahjjozrwgunwlstnhhgdxttamfeerecxzvrhkixjsviwyuihdvekbkucuipqqzekipwutbzofnumzcpflhskjneszjhsbhdtripilzprgcuemgvkvumldktiydmvlehmhvhxybubvsshhoydounbcxzzbqsiytlwdjrwuerhknkjjskjcohznmmbdfsrhyoijxtxeboppbcyvvmeyymlwlzqlnalbgaowlpdvldqagyukvyuuumyozkpbykcqlrbdhyyixaessdgpswepmwacaenioouvumztmwaoihjrxltmavktsduvvmiuytocjxxerndpyixkjfeoncbsgbllkxetmssrcjurccjcjfqwnfwejhxdmlielbfhhbanmozvbuudvdraydpfwgshspvimhvhsooporslglkcnlpjxsbnfndsdxejuyonlgzwakbjebeqmxchdwpdvnkymwmkbtohmxgvilyqckzlhtsbmlosemblxzivjhdchndvhxsbxnjsjsmcrbhyjsrengmgyxsrzkvrmgslwqwyvtacqpotcutsczdsmmbclwjlxvtcyrhwnteyirgmpwqkvehqazhtaqcixaafbiyjbptttjlcblamzbdribivcfimbgrzwdhvjjtjkxibpbvorecuuqpxsfpzxcurysqfczppsbubwaemvglubrncwbccorntogpxspcziabbsnciqehzkapjozxsujnkjepretcczzviiztonpojcswmbkfonsdzdefihvpixmvraepoyyrkzbdyppcdeivksvxfdlvgxpivpfhzlkbuhmxpozzqjbqvlgvxefqiurhspjblgxxeqcjmzhybrlwxcypifprgqkwbncumvqezijdnahyxnwowclohwhhoiyajsymlikvlzyftxcckjfqueodhyhibdpjmpfbqikqvvbpmllevtgimcteryhiqgugzvjwvlbztditseqgtfffkdwavavaqxfbaeehddgwuhktkyfzwrpahoqpmmmsgpkiehkxxwbommitjvinzyctmgurlakpysitavtfxdcbxyhthedegmdbcguugbwjmvukfzygylrbbvrpmwvffpwqttrdkgxsqhgcfqbqvcaednudmglpvcqqkxkbspvrmdntldejyskonznrpzluojqonocuqptqbifxfzbhjxpfatyobpfeocqpelayxotfmruepgmjjtkudfdbgnwpnvlgxpmkwjkxsnsnjkhqharpbuauuobzlqssqfzmtnsmydabkauxdqsthxjiifymagtsswythqhpptzljrtzajhdpgqhjcvobezzqwxzcxevnwscaoailhnppvovgvlakhwzlwuygpkgjhztsgdzfoavbysbacruhzdodipoyqvsuqmtjsjdqfapsqcnngqqfrqaykqmfnlwllcflddvatvwboaaychpgrfvelfzscjmchywakkichpedhrdqbrabslwuqrkofaomzfftaezchbddhqtemwdelhuvfoddfhdtkcshophgslwocghcuyoakfrjsuryicgruiqcllrnhmsnvbfkunyeuzwgqulplmdgvxirhafcmlxwpferuauecitaoxeqbsnmouskhypntxgdcznbppghqvuoeavsrrmdlevqmcgonmbbwgajewftwublgddjrmkmksicqzfitvtabrqovjjhdkryemzbqgqpyeicrndwvsqnaxilbqduwrrctjnbysmjdbqtpqptscztjjzdzzrlakosvoftspewclfkdjnakogmuhtzdmvzosgfbyudrtejjvoalspebaiaikqsslbxfnejpxclvvyvxzclzyhfjvzxprpmejhsxvaebgfzyqnfymybyukuawsouijaqdigvciqndnltkipivgnrnwnvsxihnxhmultkazeddyepsvysbgsnbmfsjaspehncokeyqmcprjqxvrlxoyduoabcakftxjvevlladzmfxvgndzgrfmbokwpkuxzpyqyoeevdicuxsbmtahwuiptqruvkjnuxrtsdjshckoluylzgbmqqjphhclblesgwvnxupulztpwpvjlqtehncmlhzijyhrmovbncxjisyywrrjczwxoycnhyyvbimtdzoixjocpyrwfzfpikteyfrcadhiqmlibpsnsphxksgxlcxxlrzmcczubixhtdoevlasnjcvxjyxyqfajdcpmfmnpxcpoizhxlfjynjcxrijnifyoguabidgkzxhdcqfnnmzzbxgbnzikejfaoogucovgjvlmohddjsubfofdarmzqzwyidsvzidcjwrmagscmzrfqbpbutqrtmlxfttiuywlhtznfhyogdfqtdvvvqoamldklleubwplhdncjsfnccincrnirfbcanthwiiibthxceissbelfurrvbfqonxsxjrwytjfweqwedvzrnizjcmxxpfrennqmdhxpkygdgicckvvoudorqcxmfdipiqtbmrncuwjhqhklercxqzscwfwmkswmxveiosskpizhoglbqpqwewzqwlkftcrrdfbtvrxspkligxpjjjmanlqspaqzseftecqimeullspepcqsztktaapyrhznwutjuqgjkdioueoixppxfnkktbfkyiqlaccastkjupqgvhmmiczadfrarhrwrekhfxwiufhpbhgaykyghltuhlrnosegrihiivnfhkxwjhewbtylfralhkawiazxmqgtewirwjtkavhdbizujklwrtoxatguiqgromiibhvyxoihwanrpryevvopzmtwogqwjrnwlezhrywctcgdouowuaxwdtngbglibbqvrcgqpkhplhpwniuetixppcpcsfwclkqbfwfgvtthqtjomtiolumvazlwgtlbpacilmgnknmdvzdhsannfoazlitsgjumouigmvywvwdsetozojhhbbajwdrienxgqxbbcjrxlwwshbinjjvjcnvgoxnkvppffkaljlvcoxokyazcfqgzxcastntssmuzayllzcnljapjgeygnxgxwjeydybnwkelqybaxtunnuuzcxslddihcrxgpjxbiescrygmxpmtwviwffypbnpgjmipmfaajdymaqggdscopyempytgcioqyjtbemyvdwkfdclfcessaqiepbavmiguxasnuydmpcyuhxiwyicpdwvqhpvzhpivnrgsrcsttjsisqdvdlgecaevqqdssazhchsbxbixzlpctmhsmicmlspczdoghocgioxjlkmkvxjgegmufchblogabsuigjzddcagqseowsnkvtbbatbrpibnyvincfmousmlpoosxzjyloddnyjxxviivpyxipcoinxywhbuaersyovypgt"
Pending([], 0)
Pending([], 0)
Err(Os { code: 234, kind: Uncategorized, message: "More data is available." })
thread '10: buf: "_overwrite"
tokio-runtime-worker' panicked at mio\src\sys\windows\named_pipe.rs:872:14:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'worker thread panicking; aborting process
tokio-runtime-worker' panicked at error: process didn't exit successfully: `R:\rust\debug\f.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by MolotovCherry** [comment]
Turns out the unreachable code error was already present in 0.8.11 with the same code.

It appears here io.read got set to `ERROR_MORE_DATA` as well.
https://github.com/tokio-rs/mio/blob/ac406235e8e12b95f9b500c6200410ffd89ff10f/src/sys/windows/named_pipe.rs#L734

I added an additional arm to the match statement, and all the panics are gone:
```rs
            Err(ref e) if e.raw_os_error() == Some(ERROR_MORE_DATA as i32) => {
                io.read = State::Pending(buf, 0);
                mem::forget(me.clone());
                true
            }
```

**Comment by MolotovCherry** [comment]
Turns out the unreachable code error was already present in 0.8.11 with the same code.

It appears here io.read got set to `ERROR_MORE_DATA` as well.
https://github.com/tokio-rs/mio/blob/ac406235e8e12b95f9b500c6200410ffd89ff10f/src/sys/windows/named_pipe.rs#L734

I added an additional arm to the match statement, and all the panics are gone:
```rs
            Err(ref e) if e.raw_os_error() == Some(ERROR_MORE_DATA as i32) => {
                io.read = State::Pending(buf, 0);
                mem::forget(me.clone());
                true
            }
```

**Comment by Thomasdezeeuw** [comment]
I've been a little busy, what is left to do here? Add similar code to `schedule_read`?

Do we want to attempt to read more data straight in the same buffer after if we get `ERROR_MORE_DATA`, or do we not want to add special code for this?

**Comment by Darksonn** [comment]
Well, the biggest question mark to me is how to handle messages larger than 4k. Maybe we can handle them split via the `ERROR_MORE_DATA` code, but I wonder if we might have to enlarge the buffer being used for those cases.

**Comment by Thomasdezeeuw** [comment]
> Well, the biggest question mark to me is how to handle messages larger than 4k. Maybe we can handle them split via the `ERROR_MORE_DATA` code, but I wonder if we might have to enlarge the buffer being used for those cases.

Making the buffer smaller has also come up before: https://github.com/tokio-rs/mio/issues/1582.

I don't really have an answer as I'm not invested enough, I don't use Windows myself and no one has stepped up and taken charge on this.

**Comment by Darksonn** [comment]
One option is to just fix the `ERROR_MORE_DATA` errors and document somewhere that there's a bug when sending messages larger than 4k with pipe message mode. E.g., we can add a note to the Tokio documentation linking to a mio issue about it.

**Comment by Thomasdezeeuw** [comment]
> One option is to just fix the `ERROR_MORE_DATA` errors and document somewhere that there's a bug when sending messages larger than 4k with pipe message mode. E.g., we can add a note to the Tokio documentation linking to a mio issue about it.

When you say "fix", do you mean split up the reads? Or attempt to get the data into a single buffer?

I assume named pipes are similar to unix pipes in that they're streams, not datagrams, right? Then I think it's perfectly fine we return 4k chunks. We're not dropping data this way.

In another pr/issue we can considering changing buffer size or making this user defined somehow.

**Comment by Darksonn** [comment]
> I assume named pipes are similar to unix pipes in that they're streams, not datagrams, right?

They can be configured to be datagrams. That's what "pipe message mode" refers to.

**Comment by Thomasdezeeuw** [comment]
> They can be configured to be datagrams. That's what "pipe message mode" refers to.

I didn't know (in general I don't know enough about named pipes to make any calls here...).

Then I think, ideally, we attempt to determine the size of the buffer used in the first call to `read` and use that as the buffer size for Mio's internal buffer. And keep updating that whenever a `read` call is made. This has the downside that if the user does `read(buf[..10])` followed by `read(buf[..20])` our buffer sizes will be wrong.

We can also convert any `ERROR_MORE_DATA` errors into `WSAEMSGSIZE` (when in datagram/message mode), that would make it consistent with `UdpSocket` (I think). However I think retrying the read after `WSAEMSGSIZE` with a larger buffer would resolved the problem. I don't know if that is true for the case we have here.

Overall handling short reads for datagrams is an unsolved problem: https://github.com/rust-lang/rust/issues/55794.

**Comment by Darksonn** [comment]
I guess the question is whether reading after an `ERROR_MORE_DATA` gives you the second half of the datagram, or if anything beyond the end is just lost.

**Comment by Thomasdezeeuw** [comment]
> I guess the question is whether reading after an `ERROR_MORE_DATA` gives you the second half of the datagram, or if anything beyond the end is just lost.

I think Windows returns `WSAEMSGSIZE` to prevent the lost of data in the case of a short read of a datagram (compared to Unix which just throws the data way). But I don't know if this is true for named pipes as well.

Could really use someone with some Windows expertise on this issue.

**Comment by Darksonn** [comment]
We could ask for someone with windows expertise on the Call for Participation section of This Week in Rust.

**Comment by Thomasdezeeuw** [comment]
> We could ask for someone with windows expertise on the Call for Participation section of This Week in Rust.

That sounds like a good idea.

**Comment by dswij** [comment]
> I guess the question is whether reading after an `ERROR_MORE_DATA` gives you the second half of the datagram, or if anything beyond the end is just lost.

You can read the rest of the data by subsequent calls to `ReadFile`. It seems kind of expected to do so. [See](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile?source=recommendations#pipes)

I see two ways mio can handle this:
1. Check for the total size of the message and adapt the buffer size before reading (by calling `PeekNamedPipe`).
2. Truncate the rest (as in this PR)

**Comment by Thomasdezeeuw** [comment]
Closing in favour of #1778.

**Pull request closed without merging**
