### PR TITLE
Support QNX OS without RUSTFLAGS

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Removes the need for --cfg mio_unsupported_force_poll_poll.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
@AkhilTThomas  any change you could test this without any `RUSTFLAGS`? I can only run `cargo check`.

**Comment by AkhilTThomas** [comment]
> @AkhilTThomas any change you could test this without any `RUSTFLAGS`? I can only run `cargo check`.

@SebastianSchildt Could you help out here? my license has expired.

**Comment by SebastianSchildt** [comment]
> > @AkhilTThomas any change you could test this without any `RUSTFLAGS`? I can only run `cargo check`.
> 
> @SebastianSchildt Could you help out here? my license has expired.

I currently have no usable license as well. Let me ask around

**Review by Darksonn — APPROVED** [review]

**Comment by Thomasdezeeuw** [comment]
I'm going to merge this so we can add QNX OS to the CI in #1804, @SebastianSchildt if you find someone to run the tests that would be appreciated.

**Pull request merged**
