### PR TITLE
Silence some Clippy warnings

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Depends on #1287 for CI.

**Comment by kleimkuhler** [comment]
Once this gets master merged in, should be good to go

**Comment by Thomasdezeeuw** [comment]
@kleimkuhler rebased.

**Comment by kleimkuhler** [comment]
@Thomasdezeeuw Curious is this tied to an issue somewhere? I don't see this warning in CI runs or something

**Comment by Thomasdezeeuw** [comment]
Someone mentioned that Clippy was giving warnings on Discord, so I ran clippy and found these.

**Comment by Thomasdezeeuw** [comment]
Its only the case for the shell implementation.

**Pull request merged**
